### ISSUE TITLE
Dead data link in handle_data.ipynb

### ISSUE THREAD

**Issue by davidtvs** [tomassosorio/DeepLearning#36]
In [handle_data.ipynb](https://github.com/tomassosorio/DeepLearning/blob/workshop/workshop/handle_data.ipynb) the data link is dead. Should probably be replaced by the source website (https://www.kaggle.com/c/dogs-vs-cats/data) or, to avoid signing up and giving the phone number to the source website, we can use [dropbox](https://www.dropbox.com/sh/9om67bxpvx17nxu/AAB-OEIlVCqiHNDXd0i-4Ulia?dl=0)

**Comment by tomassosorio** [comment]
Hi,
I was already told about that problem, https://github.com/tomassosorio/DeepLearning/issues/30
Currently, I am reviewing the workshop.
In the README.md file is the kaggle dataset, and during the workshop, the data will be available on a usb drive. I find useful to have the reference to the kaggle website in the workshop since is one of the most important about competitive ML and Data Science problems, and is who gather the data.

**Comment by tomassosorio** [comment]
https://github.com/tomassosorio/DeepLearning/blob/workshop/workshop/handle_data.ipynb

Update and revise.
